# -*- coding: utf-8 -*-
"""webscrapping

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10r4CCN2jIRJ1LPqdZwITp4iWlc1HrI2w
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

i = requests.get("https://en.wikipedia.org/wiki/Yuvan_Shankar_Raja")
j=i.content
doc= BeautifulSoup(j,"lxml")
doc

table = doc.find_all("table")
ta = table[0]
ta

df1.shape

ta.find("th").get_text()== "#"

from pandas.io.formats.style_render import DataFrame
df = pd.read_html(str(ta))
df1 = pd.DataFrame(df[0])
df1

df1.to_csv('webscrapping.U1')

df1.info()

df1.describe()